name: ci-live

on:
  workflow_dispatch:
    inputs:
      epoch:
        description: "Epoch number to anchor/artifact"
        required: true
        default: "1"

jobs:
  live_or_dry:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "hello from ci-live; epoch=${{ github.event.inputs.epoch }}"
          # Produce DRY artifacts (no secrets / network)
          echo '{"weights":[0.1,0.2,0.3]}' > aggregated_model.json
          echo '{}' > client_update.enc.json
          echo '{"cid":"drycid","size":0,"url":"ipfs://drycid"}' > upload.json
          echo '{"enclave":"dev","mrEnclave":"0x00","nonce":"test"}' > attestation.json
          echo "{\"artifacts\":{\"globalModelHash\":\"0x00\",\"globalModelCid\":\"drycid\",\"globalModelUrl\":\"ipfs://drycid\"},\"provenance\":{\"attestationHash\":\"0x00\",\"commit\":\"HEAD\",\"mode\":\"dry\"},\"epoch\":${{ github.event.inputs.epoch }},\"network\":{\"chainId\":\"16601\"}}" > market_manifest.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
        with:
          name: ci-live-${{ github.run_attempt }}
          path: |
            upload.json
            aggregated_model.json
            client_update.enc.json
            attestation.json
            market_manifest.json
