      - name: Encrypt sample client update (smoke)
        continue-on-error: true
        run: |
          echo '{"round":${{ github.event.inputs.epoch }}, "weights":[0.01,0.02]}' > client_update.json
          if [ -f dist/crypto/encrypt_update.js ]; then
            node scripts/encrypt_update_loader.js client_update.json --out client_update.enc.json
          else
            echo '{}' > client_update.enc.json
            echo 'WARN: dist/crypto/encrypt_update.js missing; emitted placeholder client_update.enc.json'
          fi
          ls -l client_update.enc.json