name: ci-no-tx
on:
  push:
    branches: [ rao ]
  workflow_dispatch:

jobs:
  round-no-tx:
    runs-on: ubuntu-latest
    env:
      NO_TX: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install deps (non-fatal)
        continue-on-error: true
        run: |
          set -euxo pipefail
          npm ci || npm i || true

      - name: Build (non-fatal)
      # continue-on-error via shell fallback
        run: |
          set -euxo pipefail
          npm run build || true

      - name: Init CI log
        run: echo "started $(date -u +%FT%TZ)" > ci.log

      - name: Upload CI logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-${{ github.run_id }}-${{ github.attempt || github.run_attempt }}
          path: |
            ci.log
          if-no-files-found: warn
