# // GitHub Actions smoke: build + policy + sha evidence (no storage/CID required)
name: ci-smoke

# // Trigger on rao branch
on:
  push:
    branches: [ rao ]
  pull_request:
    branches: [ rao ]

# // Single Windows job for parity with dev environment
jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm ci
      - name: Compile (Galileo)
        run: npx hardhat compile --config .\hardhat.galileo.js
      - name: Aggregate (deterministic)
        run: node .\dist\local_normalize_and_aggregate.js --in-dir . --out-dir . --on-mismatch pad --force-path '$.weights'
      - name: Compute sha256 evidence
        shell: pwsh
        run: |
          $b=[IO.File]::ReadAllBytes('aggregated_model.json')
          $sha=[BitConverter]::ToString((New-Object Security.Cryptography.SHA256Managed).ComputeHash($b)).Replace('-','').ToLower()
          "{`"file`":`"aggregated_model.json`",`"size`":$($b.Length),`"sha256`":`"$sha`"}" | Set-Content -Encoding UTF8 aggregated_model.storage_meta.json
      - name: Attestation allowlist check
        run: node .\scripts\attestation_enforce.js --attestation .\attestation_example.json --allowlist .\attestation_allowlist.json
      - name: Encryption/plaintext guard
        shell: pwsh
        run: powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\guard_plaintext.ps1
      - name: Upload evidence
        uses: actions/upload-artifact@v4
        with:
          name: evidence
          path: |
            aggregated_model.json
            aggregated_model.storage_meta.json
